name: Deploy to Vercel

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Vercel
        uses: vercel/actions@v2
        with:
          vercel-token: 1Fhnyl8VtORySFSXueq8kNyS
          vercel-args: |
            --prod
